### ISSUE TITLE
Startup slow due to fsGroup with large data volume

### ISSUE THREAD

**Issue by raxod502-plaid** [runatlantis/helm-charts#14]
Cross-posting from https://github.com/runatlantis/atlantis/issues/342#issuecomment-731363597 for visibility. The Atlantis chart uses the `securityContext.fsGroup` option to initially set filesystem permissions. I presume this is because persistent volumes are often initialized to have a filesystem owned by root. However, `fsGroup` causes Kubernetes to run a recursive `chown` on the entire volume at every startup. For a large data volume with many clones of large repositories, this can take upwards of 10 minutes. Since Atlantis runs as a singleton this equates to 10 extra minutes of downtime on every deploy.

In our private fork of Atlantis I have dealt with this problem by doing the recursive `chown` in the Docker entrypoint, if and only if the top-level directory is not owned by the Atlantis user. Kubernetes now provides this feature natively, but only in alpha: see [fsGroupChangePolicy](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#configure-volume-permission-and-ownership-change-policy-for-pods).

**Comment by raxod502-plaid** [comment]
I thought I tested this when originally setting up the PR, but it was about a year and a half before it was merged, so it's possible something changed since then, or that I have a bad recollection.

**Comment by yuha0** [comment]
`fsGroupChangePolicy` has been a beta feature since 1.20, so I think the merged change is not required anymore?

In fact this change broke our deployment because we enforce a non-root user for atlantis container, which cannot `chown`

**Comment by jamengual** [comment]
are we saying that this should be reverted?

**Comment by jamengual** [comment]
Yes, there were some issues on the releases, now we have a new process and
we will continue to improve it.

**Comment by jamengual** [comment]
After looking at the change 
```
securityContext:
    fsGroup: 1000
    runAsUser: 100
```

which removes the `RunAsUser` it makes atlantis to run as root by default which is definitely a bad idea, we want Atlantis to be secure by default and I agree with @yuha0 on that point.

People that need to run it as root, can change the values on the chart since is already exposed.

**Comment by gmaghera** [comment]
Hmm, I see it run as atlantis inside the pod, and when I deployed a new version of the chart and image I saw file ownership updates indicating the contrary.  I saved a screenshot to share with my coworkers that we now have both sides of the implementation.

![image](https://user-images.githubusercontent.com/940137/174899056-2cca3237-21ea-4755-86f1-7f1ba420419b.png)

This is from inside the pod from Helm chart 4.0.3 using our own image, based on Atlantis 1.9.4:
```
bash-5.1# ps -ef
PID   USER     TIME  COMMAND
    1 root      0:00 {docker-entrypoi} /usr/bin/dumb-init /bin/sh /usr/local/bin/docker-entrypoint.sh server --enable-policy-checks
    7 atlantis 34:39 atlantis server --enable-policy-checks
  659 root      0:00 sh -c clear; (bash || ash || sh)
  666 root      0:00 bash
 5674 root      0:00 bash
 5680 root      0:00 ps -ef
32567 root      0:00 /bin/bash
```

**Comment by jamengual** [comment]
I just merged and updated the chart, did you use the new chart ?

**Comment by gmaghera** [comment]
That screenshot was taken Tuesday on June 14th using chart version 4.0.3.

**Comment by nitrocode** [comment]
can this be closed after merging #156 and #158?

**Comment by gmaghera** [comment]
@nitrocode IIRC the improvement was rolled back for some reason.

**Comment by nitrocode** [comment]
That was #156. Did you see #158?

**Comment by nitrocode** [comment]
Closing due to merging of #158
