### ISSUE TITLE
Add Annotations to secrets

### ISSUE THREAD

**Issue by ekhaydarov** [runatlantis/helm-charts#140]
Currently there are annotations available to `statefulSet` and `podAnnotations`.  Looking through [secret-webhook.yaml](https://github.com/runatlantis/helm-charts/blob/main/charts/atlantis/templates/secret-webhook.yaml#L5) we can see that only labels are added. Would it be possible to allow to annotate secrets, or in fact all the k8s objects?

**Comment by GMartinez-Sisti** [comment]
We could ensure all the objects have annotations, along with a global annotation that would be included on all resources when defined.

Should I implement this?
