### ISSUE TITLE
Add Automatic Changelog generation to this repo

### ISSUE THREAD

**Issue by jamengual** [runatlantis/helm-charts#157]
Add Changelog to this repo and automatic Changelog generation for releases

**Comment by nitrocode** [comment]
Maybe we could use one of these options

- https://github.com/marketplace/actions/release-changelog-builder
- https://github.com/semantic-release/changelog

Have you used something in the past that would be handy here?

**Comment by jamengual** [comment]
I have not, we could use something similar to the atlantis repo?

**Comment by nitrocode** [comment]
It looks like we use goreleaser for Atlantis for non pre releases and a gh api command for pre releases. We cannot use goreleaser here but we could use the gh api command method.

https://github.com/runatlantis/atlantis/blob/fe4915a6fcc790cc29f7798f662147db00f74712/.github/workflows/release.yml#L31

**Comment by GMartinez-Sisti** [comment]
Implemented on https://github.com/runatlantis/helm-charts/pull/302.
