### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by DavidPessoa** [runatlantis/helm-charts#200]
Hello,

Thanks for all of the effort on maintaining this repo.

I would like to propose the adoption of a changelog for this repo. The reason why is because a new version was just released but I don't know what changes were made without checking PRs. 
Does this make sense?

Thank you once more

**Comment by nitrocode** [comment]
Hi David. Thank you for writing this ticket, however, this seems to be a duplicate of https://github.com/runatlantis/helm-charts/issues/157 so I will close this and we can continue the discussion in the other ticket.
