### ISSUE TITLE
Add support for not specifying a host

### ISSUE THREAD

**Issue by davidh-unmind** [runatlantis/helm-charts#201]
Am I being dumb or have you built the ingress template in such a way that it is not possible to specify "*" any host. During testing I don't care much for the host and found this annoying.

**Comment by nitrocode** [comment]
@davidh-unmind you should be able to set the `host` to anything acceptable in the `Ingress` kind spec

https://github.com/runatlantis/helm-charts/blob/a4e46785625115d3c280fc3337754c0fa5a9f670/charts/atlantis/templates/ingress.yaml#L36

Try these values

```yaml
ingress:
  host:
    name: *
```

If that doesn't work, please propose the necessary change

**Comment by nitrocode** [comment]
Oh I think I understand, you'd like to completely omit the `host` key and it may not be possible at the moment. Is that right?

https://github.com/runatlantis/helm-charts/blob/a4e46785625115d3c280fc3337754c0fa5a9f670/charts/atlantis/templates/ingress.yaml#L35-L38
