### ISSUE TITLE
Altantis can't start using GitHub App configs.

### ISSUE THREAD

**Issue by weyderfs** [runatlantis/helm-charts#206]
Hi guys,
I would like to use Atlantis + GitHub App installed at my Organization. 

But I have been troubles when switch configs (after having started correctly using `github` parameters with fake data) or trying start deployment using directly the `githuApp` definitions at `values.yaml`. To be more precise [this](https://github.com/runatlantis/helm-charts/blob/main/charts/atlantis/values.yaml#L22-L29) parameters.

https://github.com/runatlantis/helm-charts/blob/97642c829d4754dcb3b0677e5c7da27c4e792971/charts/atlantis/values.yaml#L22-L29

Always returns: `Error: initializing server: error initializing github authentication transport: wrong number of installations, expected 1, found 2`.

It's sounds like such the Atlantins ignores the new parameters in the `githubApp:`.

At first moment I thought, maybe I made a mistake let something uncommented, but I've checked the code and no. So Atlantis only starts using the `github` values at `values.yaml`

Anyone else had a similar problem?

**Comment by nitrocode** [comment]
Could you share your full list of inputs?

Could you try using `helm template` to see the generated yaml spec and see where the issue may be?

There must be something wrong with how the chart is generating the spec.

**Comment by weyderfs** [comment]
I managed to solve it by trial and error.

**Comment by nitrocode** [comment]
@weyderfs please share your solution with us so we can fix or document it for others
