### ISSUE TITLE
Doubt about how to consume secrets of K8s

### ISSUE THREAD

**Issue by weyderfs** [runatlantis/helm-charts#213]
Guys,
Someone have a example or template file to create a k8s secrets using these parameters at `values.yaml`?:

- [awsSecretName](https://github.com/runatlantis/helm-charts/blob/main/charts/atlantis/values.yaml#L89)
- [gitconfigSecretName](https://github.com/runatlantis/helm-charts/blob/main/charts/atlantis/values.yaml#L75)

I've already tried using the file I have that works and I also tried using the example from `values.yaml` itself
I haven't been able to use any...

**Comment by nitrocode** [comment]
@weyderfs were you able to figure it out?

Did you use helmfile to retrieve the secret and pass it to the chart?

or perhaps create a secret outside of this helm chart and then mount it into the pod?
