### ISSUE TITLE
gitconfig credential.helper error: Resource busy

### ISSUE THREAD

**Issue by kpettijohn** [runatlantis/helm-charts#222]
It seems with the changes made in #203 Atlantis now throws an error when attempting to modify the git config.

https://github.com/runatlantis/helm-charts/pull/203/files#diff-a3b675e5633e3d9602003c23ede42b91c32bc10f4aed39235b204cff10c11bbdL131

```
{"level":"error","ts":"2022-12-02T16:15:07.444Z","caller":"events/command_runner.go:169","msg":"Error running pre-workflow hooks There was an error running git config --global credential.helper store: error: could not write config file /home/atlantis/.gitconfig: Resource busy\n: exit status 4. Proceeding with plan command."}
```

Overall I believe this is due to changing the mount path to be `/home/atlantis/.gitconfig` instead of mounting the file to `/etc/secret-gitconfig` and copying the file to `/home/atlantis/.gitconfig`. This causes the `/home/atlantis/.gitconfig` file to be read only so when [Atlantis attempts to run `git config --global credential.helper store`](https://github.com/runatlantis/atlantis/blob/main/server/events/git_cred_writer.go#L55) it results in the error `Resource busy`.

It seems due to this error it causes all additional pre workflow hooks to be skipped which causes additional issues. I'm not totally sure what the best path forward is here. In our setup we include the git credential configuration as part of the `gitconfig`.

```
            gitconfig: |
              [credential]
                helper = store
              [url "https://x-access-token@github.com"]
                insteadOf = ssh://git@github.com
              [url "https://x-access-token@github.com/"]
                insteadOf = git@github.com:
```

Any ideas to fix or work around the issue would be appreciated!

**Comment by nitrocode** [comment]
Thanks @kpettijohn for bringing this to our attention.

@kpettijohn @nxf5025 could you see if there is a small change to fix this?

**Comment by GMartinez-Sisti** [comment]
Possible fix on https://github.com/runatlantis/helm-charts/pull/384. Please review.

**Comment by bdellegrazie** [comment]
Just FYI, this isn't fixed as the volume mount is still mounted read-only.

**Comment by GMartinez-Sisti** [comment]
> Just FYI, this isn't fixed as the volume mount is still mounted read-only.

Yes! We are aware of that 😓 Recent discussions were [here](https://github.com/runatlantis/atlantis/issues/1257). Re-opening !

**Comment by GMartinez-Sisti** [comment]
Hi! Please take a look at https://github.com/runatlantis/helm-charts/pull/407, to confirm this fixes the issue. 🙏

**Comment by qdm12** [comment]
Hello there,
I am facing the same issue but on another project (bind mounting .gitconfig in a dev container).
@kpettijohn  you mention

> This causes the /home/atlantis/.gitconfig file to be read only

Why is that? Why is mounting directly to `~/.gitconfig` making this read-only for `git`?? In my case I bind mount without forcing read-only in a container with `-v /home/user/.gitconfig:/home/user/.gitconfig` and get that `resource busy` error as well. Is bind mounting making git unable to modify the file? On top of this, manually editing the file (i.e. with `vi`) works fine...

**Comment by mubarak-j** [comment]
@qdm12 I'm not sure why `read-only` is the default but you can override it using `gitconfigReadOnly: true` in the [helm values](https://github.com/runatlantis/helm-charts/blob/0f179ba7462b2815bdc4d6387a4ead53a7f762e3/charts/atlantis/values.yaml#L114-L117) which was added in [v5.4.1](https://github.com/runatlantis/helm-charts/commit/58ecee792e1c35fdcb3d322c41a7a3828c334ff4#diff-1df930d196169691f5ef5f98b8292e2ae77de84eed83162288bd50b22870192eR6) of this chart

**Comment by awesomebytes** [comment]
> Why is that? Why is mounting directly to ~/.gitconfig making this read-only for git?? In my case I bind mount without forcing read-only in a container with -v /home/user/.gitconfig:/home/user/.gitconfig and get that resource busy error as well. Is bind mounting making git unable to modify the file? On top of this, manually editing the file (i.e. with vi) works fine...

I'm in the same boat, and confused.
