### ISSUE TITLE
Helm chart: support adding providers/plugins

### ISSUE THREAD

**Issue by MPV** [runatlantis/helm-charts#227]
Currently, when installing Atlantis using the `stable/atlantis` Helm chart and you want to add/use custom providers/plugins, you need to extend the Atlantis Dockerfile and add plugins. 

While this works, it adds/requires the lifecycle of a new Docker image, which might not always be desirable. 

**I’d like to suggest we add support for installing plugins using the helm chart.**

For example: using an initContainer that runs some commands to download and extract the desired plugins to their right place.

The readme of the chart could describe example commands to use for enabling the functionality and for installing some plugin.

**Comment by GMartinez-Sisti** [comment]
Is this still desired? I can implement this feature by adding the option to mount a shared volume to the `initContainers` list. Any plugins can then be installed there and then Atlantis would use them.

https://github.com/runatlantis/helm-charts/blob/e7429090d8a0150126b4e6d29c451ec679628d24/charts/atlantis/values.yaml#L447C9-L451

**Comment by jamengual** [comment]
I like the flexibility but it adds a bit is a bit scary since you could potentially install a compromised plugin etc. I guess if we document the option security concern it should be fine.

**Comment by GMartinez-Sisti** [comment]
I share the concern, but in reality it's not much different than creating a custom image. We can also add a couple of examples for some common plugins (terragrunt, sops) with checksum validation to support good practices. WDYT?

**Comment by GenPage** [comment]
I think this is a great idea and could provide a great way to de-clutter the the main docker file as well for the official image.

**Comment by GMartinez-Sisti** [comment]
This can be assigned to me then please.

**Comment by bertinmeshita** [comment]
Is there a time estimation for this?

**Comment by GMartinez-Sisti** [comment]
> Is there a time estimation for this?

I'll see if I can get to it this weekend! 😅

**Comment by GMartinez-Sisti** [comment]
PR created -> https://github.com/runatlantis/helm-charts/pull/310 please comment and suggest 🚀
