### ISSUE TITLE
Automatically generate README from helm values

### ISSUE THREAD

**Issue by Teko012** [runatlantis/helm-charts#230]
Ideally, the README should be automatically generated by the CI. 

Some of the possible options for tooling:
- https://github.com/norwoodj/helm-docs
- https://github.com/kubepack/chart-doc-gen
- https://github.com/bitnami-labs/readme-generator-for-helm
- https://github.com/rapidsai/frigate

Once the tool has been decided, the `values.yaml` can be reformatted accordingly.

**Comment by Teko012** [comment]
I went through the chart to see what are the missing values in `values.yaml`, which need to be added first (I was only looking if something can be supplied as value but missing from the `values.yaml` file).

The values that are missing from the `README` currently and from the `values.yaml`:
```
basicAuthSecretName
fullnameOverride
nameOverride
```
These are in the `README`, but not mentioned in the values.yaml:
```
command
config
environment
ingress.apiVersion
orgWhitelist
service.annotations
service.loadBalancerSourceRanges
```

All of this will need to be added to the `values.yaml` file. I haven't checked if there are any that are still mentioned in the `README`, and not in the code, but I don't think that matters, and it will be fixed when it gets auto generated.

**Comment by Teko012** [comment]
I think [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm) might be better for this, but [helm-docs](https://github.com/norwoodj/helm-docs) could work too, both lets you specify types.

**Comment by Teko012** [comment]
We should also unify what is declared by default and what is not: https://github.com/runatlantis/helm-charts/pull/238 We will have to check if declaring it as an empty value will change some behaviour or not.

**Comment by GMartinez-Sisti** [comment]
I'll take this one.
