### ISSUE TITLE
.Values.github.user cannot be evaluated in 4.8.2

### ISSUE THREAD

**Issue by Jeinhaus** [runatlantis/helm-charts#236]
As mentioned in https://github.com/runatlantis/helm-charts/commit/02acd2515c39a33a261762d8f384a9d528752a16#r94788606 this check does not work if no `github` key is present in the `values.yaml` file.
We currently use Gitlab, so no `github` configuration is required. This leads to the following error when upgrading to 4.8.2:

```
executing "atlantis/templates/statefulset.yaml" at <.Values.github.user>: nil pointer evaluating interface {}.user
```

I think the check should either be reverted to `{{- if .Values.github }}`, an additional check on `github.user` added to the previous check, or an empty map `github: {}` added to the `values.yaml`.
I'd be willing to provide a PR, if that helps.

**Comment by nitrocode** [comment]
Nice catch. Please feel free to propose the change or perhaps @Teko012 may have a chance in mind?

**Comment by Teko012** [comment]
Indeed, I would probably add it as an empty map for now: `github: {}`. I will create a PR. I think it ties into https://github.com/runatlantis/helm-charts/issues/230 as well in the future, right now its a mix what is declared and what is just a comment.
