### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by nitrocode** [runatlantis/helm-charts#239]
It would be nice to test out the helm chart using unit tests.

This has come up a few times since contributions can introduce breaking changes.

Options

1. Using https://www.phillipsj.net/posts/yes-you-can-unit-test-helm-charts/ with golang and terratest
2. Using https://blog.ediri.io/how-to-unit-test-your-helm-charts with [quintush/helm-unittest](https://github.com/quintush/helm-unittest)
3. helm test
    - The command `helm test` is more of an integration test since it requires deploying the chart 

Whatever is chosen, the tests should capture at least

- enabling a single vcs - test github, gitlab, bitbucket, azuredevops, etc
- tbd

**Comment by GMartinez-Sisti** [comment]
I love the idea of doing unit tests with option 2 https://github.com/helm-unittest/helm-unittest. Option 1 might provide more flexibility, but not everyone knows golang and then you have to manage go and package versions, etc. helm-unittest can be executed as a helm plugin or simply in a docker image, and I think this will provide a better experience for contributors and new comers.

I'm happy to take this so I can learn how to use helm-unittest. My first PR on this would be to create a basic scaffold to cover some simple helm chart configs such as `nameOverride` and `fullnameOverride`. We can build up from there. WDYT?

**Comment by jamengual** [comment]
awesome idea.
