### ISSUE TITLE
Release 4.10.2 Not available

### ISSUE THREAD

**Issue by jseiser** [runatlantis/helm-charts#256]
```
❯ helm repo update runatlantis
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "runatlantis" chart repository
Update Complete. ⎈Happy Helming!⎈

❯ helm search repo runatlantis
NAME                	CHART VERSION	APP VERSION	DESCRIPTION
runatlantis/atlantis	4.10.0       	v0.22.2    	A Helm chart for Atlantis https://www.runatlant...
```

**Comment by nitrocode** [comment]
Here are the most recent release actions run

https://github.com/runatlantis/helm-charts/actions/workflows/release.yaml

https://github.com/runatlantis/helm-charts/actions/runs/3969254151/jobs/6804102492 started after merge of #248 and returned

```
Discovering changed charts since 'atlantis-4.10.2'...
Nothing to do. No chart changes detected.
```

https://github.com/runatlantis/helm-charts/actions/runs/3955215202/jobs/6773736857 started after #252 merged with a similar returned response but with `4.10.1`

https://github.com/runatlantis/helm-charts/actions/runs/3949712767/jobs/6761277521 started after #251 was merged and returned with `4.10.0`

After pr #245 it kicked off https://github.com/runatlantis/helm-charts/actions/runs/3859203846/jobs/6578514755 and that was the last run to bump to 4.10.0

You can see 4.10.0 listed in the gh-pages branch

https://github.com/runatlantis/helm-charts/blob/e6359f90a9df8e2089fcd72af80f6c32ba40702f/index.yaml#L23

**Comment by GenPage** [comment]
@nitrocode This is #253 and #255, the failed runs are hidden behind re-runs that return "no chart changes" since there is a github release. We need to fix index.yaml

**Comment by GenPage** [comment]
```
~
➜ helm search repo runatlantis
NAME                    CHART VERSION   APP VERSION     DESCRIPTION
runatlantis/atlantis    4.10.2          v0.22.3         A Helm chart for Atlantis https://www.runatlant...
```
@jseiser can you confirm this is resolved?

**Comment by GenPage** [comment]
4.10.3 released successfully. See [workflow](https://github.com/runatlantis/helm-charts/actions/runs/4068159398/jobs/7006374520) I'm closing this.

**Comment by jseiser** [comment]
@GenPage 

Sorry, ive been tied up with a fluent-bit problem.  Ill confirm this ASAP.

Thanks for the work.
