### ISSUE TITLE
Add support for .terraformrc

### ISSUE THREAD

**Issue by Paulius0112** [runatlantis/helm-charts#262]
Trying to initialise private terraform modules in gitlab fails with all currently available secrets in the chart. However, manually providing a `.terraformrc` file with content 

```credentials "gitlab.com" {
  token = "<TOKEN>"
}```

works successfully. Could you please add support for the above described file?

**Comment by jseiser** [comment]
@Paulius0112 

Can you please elaborate on this?

Where does this file need to be?

**Comment by GMartinez-Sisti** [comment]
Environment variables can be configured using the `environment` key: https://github.com/runatlantis/helm-charts/blob/6ff20ced250db8c40f59bf865826831f6ef9ab12/charts/atlantis/values.yaml#L418-L420.

Does this solves this issue?
