### ISSUE TITLE
Apply is not working

### ISSUE THREAD

**Issue by stafot** [runatlantis/helm-charts#27]
I’m finding the plan works fine, but Atlantis logs the following warning on the subsequent apply: Unable to update commit status: POST https://gitlab[redacted]: 400 {message: Cannot transition status via :enqueue from :pending (Reason(s): Status cannot transition via "enqueue")}

Helm chart version: 3.12.4
VCS: Gitlab

Result: The pipeline gets stuck to pending forever.

**Comment by lkysow** [comment]
@stafot please post Atlantis issues that aren't related specifically to the Helm chart in https://github.com/runatlantis/atlantis
