### ISSUE TITLE
extensions/v1beta1 has been deprecated  since 1.16

### ISSUE THREAD

**Issue by awright-oak9** [runatlantis/helm-charts#276]
https://github.com/runatlantis/helm-charts/blob/ed1000d7b66b5fec157d8132bce66bb1765b69d4/charts/atlantis/templates/ingress.yaml#L2

extensions/v1beta1 has  been deprecated since k8s 1.16 and replaced by networking.k8s.io/v1. Can you update your template to reflect this as the default and/or add documentation stating that anyone using 1.16+ needs  to include the following in their values.yml

ingress:
    enabled: true
    apiVersion: networking.k8s.io/v1

**Comment by jamengual** [comment]
PRs are welcome.

**Comment by mattjamesaus** [comment]
Would we say that this has been solved by #280 (which is now merged)?
