### ISSUE TITLE
Support for side-car containers

### ISSUE THREAD

**Issue by collinpowerkariman** [runatlantis/helm-charts#28]
Hi Team

Any plan on adding additional side-car containers support ? I can create PR for this.

My use case is adding vault side-car to auto renew vault token.

Thank you

**Comment by pokgak** [comment]
I think this feature is already resolved in PR https://github.com/runatlantis/helm-charts/pull/65. You can specify `extraContainers` in your values files to add sidecars to the StatefulSet.
