### ISSUE TITLE
Needs to have two seperate ingresses, one for the private interface, and one for "public" facing webhooks

### ISSUE THREAD

**Issue by paul-civitas** [runatlantis/helm-charts#282]
The secure way to set up atlantis is to have two ingresses. One which is on the private network gives access to the web interface, which contains sensitive information and capabilities and needs restricted access.

The other should be used only for incoming webhooks, from github.com or similar things.

ArgoCD is set up this way. There's a applicationSet.webhook.ingress which is only for the ingress, and a server.ingress which is used for accessing the application.

With the current setup of the helm chart, someone is more likely to inadvertently expose their atlantis to the public.

**Comment by jseiser** [comment]
@paul-civitas 

Any chance you want to test this MR: https://github.com/runatlantis/helm-charts/pull/289

**Comment by paul-civitas** [comment]
@jseiser I'd be happy to :)

I've made a ticket on our internal JIRA for testing this and we'll try and get to it soon.

**Comment by jseiser** [comment]
@paul-civitas  any chance you guys got a chance to test this?

**Comment by paul-civitas** [comment]
Unfortunately not yet. I just pinged my colleague who this is assigned to to remind him to take a look at this.

**Comment by jseiser** [comment]
```
ingress:
  enabled: true
  ingressClassName: nginx
  host: atlantis.localdev.me
  path: /
secondary_ingress:
  enabled: true
  ingressClassName: nginx
  host: atlantis-webook.localdev.me
  path: /events
```


```
❯ kubectl get ingress -n atlantis
NAME                 CLASS   HOSTS                         ADDRESS   PORTS   AGE
atlantis-secondary   nginx   atlantis-webook.localdev.me             80      9s
atlantis             nginx   atlantis.localdev.me                    80      9s
```

```
❯ kubectl get ingress atlantis-secondary -n atlantis -o yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    meta.helm.sh/release-name: atlantis
    meta.helm.sh/release-namespace: atlantis
  creationTimestamp: "2023-05-25T16:21:36Z"
  generation: 1
  labels:
    app: atlantis
    app.kubernetes.io/managed-by: Helm
    chart: atlantis-4.13.0
    helm.sh/chart: atlantis-4.13.0
    heritage: Helm
    release: atlantis
  name: atlantis-secondary
  namespace: atlantis
  resourceVersion: "85793"
  uid: 3ac3c770-2c3e-4f30-881a-c6244e2c49aa
spec:
  ingressClassName: nginx
  rules:
  - host: atlantis-webook.localdev.me
    http:
      paths:
      - backend:
          service:
            name: atlantis
            port:
              number: 80
        path: /events
        pathType: ImplementationSpecific
```

**Comment by jseiser** [comment]
Then as a post, we see it gets to atlantis

```
{"level":"debug","ts":"2023-05-25T16:43:07.708Z","caller":"server/middleware.go:45","msg":"POST /events – from 10.42.0.138:59350","json":{}}
{"level":"debug","ts":"2023-05-25T16:43:07.708Z","caller":"logging/simple_logger.go:157","msg":"Ignoring request","json":{}}
{"level":"debug","ts":"2023-05-25T16:43:07.708Z","caller":"server/middleware.go:72","msg":"POST /events – respond HTTP 400","json":{}}
```

**Comment by paul-civitas** [comment]
Hey we were trying to look at this, but we ran into some difficulties that are in our end, so there's some delay. Sorry about this. We hope to be able to test this this week though.

**Comment by paul-civitas** [comment]
Hey your PR is working great in our tests! Sorry for all the delay.

**Comment by paul-civitas** [comment]
Seems to be blocked by https://github.com/bats-core/bats-core/issues/737
