### ISSUE TITLE
Is it possible to deprecate this repo in favor of stakater/application

### ISSUE THREAD

**Issue by nitrocode** [runatlantis/helm-charts#286]
ref: https://github.com/stakater/application

**Comment by nitrocode** [comment]
Hi @jseiser , could you please add some comments here.

The reason I proposed this is that it's hard to keep this project up to date and it would be nice to find easier solutions than to continue to maintain a chart ourselves.

**Comment by jseiser** [comment]
@nitrocode 

It *really* should not be too much trouble to keep it up to date.  As soon as you give up control of this chart, you will still have to answer questions from people about it, but it will be less flexible and out of your control.

**Comment by GMartinez-Sisti** [comment]
I agree that we should keep our own chart to be able to adapt and customize to the requirements of atlantis.

Can we close this? @nitrocode @jamengual ?
