### ISSUE TITLE
Helm test fails on unable to find bats/bats

### ISSUE THREAD

**Issue by rtkjbeverly** [runatlantis/helm-charts#292]
Hey,

While experimenting with this Helm chart I noticed that the helm tests are broken due to the cutover to the official `bats` image, which has an extra `v` prefix (`v1.9.0` instead of `1.9.0`) - https://github.com/runatlantis/helm-charts/commit/dfe43e99e2eff8a207e4a67a2a264fd69397d4a0.

You can see the intended image `1.9.0` on DockerHub at https://hub.docker.com/layers/bats/bats/1.9.0/images/sha256-acd28536088c346bc81f1a01d0c4c166d2a244f86ecaa486d92d6edfbf5bd258?context=explore, and validate the image by running the following:

```bash
docker pull bats/bats:v1.9.0
```

Which wil fail with `Error response from daemon: manifest for bats/bats:v1.9.0 not found: manifest unknown: manifest unknown`, while running the following will succeed:

```bash
docker pull bats/bats:1.9.0
```

This also has an issue come up with the init-containers configuration, which doesn't fit with the new image: https://github.com/runatlantis/helm-charts/blob/d8caf7944d5fc24f2daefa169076886ad7563c48/charts/atlantis/templates/tests/test-atlantis-pod.yaml#L18 as that `libexec` directory

**Comment by GMartinez-Sisti** [comment]
This should fix this issue https://github.com/runatlantis/helm-charts/pull/300.

**Comment by paul-civitas** [comment]
This is related: https://github.com/bats-core/bats-core/issues/737

**Comment by GMartinez-Sisti** [comment]
> This is related: [bats-core/bats-core#737](https://github.com/bats-core/bats-core/issues/737)

Replied on the issue.
