### ISSUE TITLE
Support for secrets instead of adding token plain into the values.yaml

### ISSUE THREAD

**Issue by Mazorius** [runatlantis/helm-charts#293]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
- If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/runatlantis/atlantis/blob/main/CONTRIBUTING.md))

**Describe the user story**

As a DevOps engineer I would like to not add my tokens plain into the values.yaml which is commited to the git repository.
From the values.yaml and documentation it is not clear if I can use secrets instead of adding the values directly.

**Describe the solution you'd like**

I would like to add the name of secrets existing in the k8s cluster so atlantis can read them.

**Describe the drawbacks of your solution**

You would have a dependency to the k8s secrets engine. But as this is a default and used by everyone that should not be a problem.

**Describe alternatives you've considered**

The current solution of adding plain text cannot be an alternative. Secrets is the only solution to that.

**Comment by zen** [comment]
You can use helm-secrets to achieve the same results with SOPS, but fully automated. PLus - it's integrated into several native DC soultions

**Comment by GMartinez-Sisti** [comment]
As mentioned, it's common practice to use a tool like [SOPS](https://github.com/getsops/sops) or [vals](https://github.com/variantdev/vals) along with [helm-secrets](https://github.com/jkroepke/helm-secrets) populate the secret in the final templated configuration, or have something else like [Hashicorp Vault](https://www.vaultproject.io/) or [External Secrets](https://external-secrets.io/latest/) create the secret and then reference the existing secret resource in the configuration.

The values.yaml file states that https://github.com/runatlantis/helm-charts/blob/6ff20ced250db8c40f59bf865826831f6ef9ab12/charts/atlantis/values.yaml#L76C3-L77:

> \# If managing secrets outside the chart for the webhook, use this variable to reference the secret name
>\# vcsSecretName: 'mysecret'

Let me know if there are any doubts.
