### ISSUE TITLE
Bump AppVersion using renovatebot

### ISSUE THREAD

**Issue by nitrocode** [runatlantis/helm-charts#295]
This was previously working

- https://github.com/runatlantis/helm-charts/pull/245 (merge jan 6)
- https://github.com/runatlantis/helm-charts/pull/252 (merge jan 18)

This may have broken it

- https://github.com/runatlantis/helm-charts/pull/248 (merge jan 20) - broken by changing `tag` to `""`
- https://github.com/runatlantis/helm-charts/pull/268 (merge mar 3) - attempt to fix
- #295

**Comment by kvanzuijlen** [comment]
@jamengual this was fixed in #268

**Comment by nitrocode** [comment]
@kvanzuijlen @jamengual I don't think it's working

https://github.com/runatlantis/helm-charts/pulls?q=is%3Apr+is%3Aclosed+author%3Aapp%2Frenovate

If it were working, we wouldn't need a mental pr from a human author

- for example, the most recent version bump #347

**Comment by kvanzuijlen** [comment]
I'll take a look at what's going on!

**Comment by kvanzuijlen** [comment]
@nitrocode You were right, there was a duplicate config file which I only saw after reading the full log output of running Renovate locally 😅. I also saw some additional dependencies that weren't being updated properly.
