### ISSUE TITLE
Breaking Change: Upgrading from 4.21.0 to 4.22.0

### ISSUE THREAD

**Issue by thomaschaplin** [runatlantis/helm-charts#379]
> This should've been a major release - breaks existing installs using the STS pv

> Yep, breaking change!

In hindsight, you are both right. Our tests install everything from scratch, but they don't contemplate upgrades.

I tested by installing `4.21.1` and then tried to upgrade to `4.22.0` and got an error:

```sh
→ helm install atlantis runatlantis/atlantis --version 4.21.1
NAME: atlantis
LAST DEPLOYED: Fri Apr  5 18:59:30 2024
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
1. Get the application URL by running these commands:
2. Atlantis will not start successfully unless at least one of the following sets of credentials are specified (see values.yaml for detailed usage):
  - github
  - githubApp
  - gitlab
  - bitbucket
```

```sh
→ helm upgrade atlantis runatlantis/atlantis --version 4.22.0
W0405 18:59:46.772125   48368 warnings.go:70] unknown field "labels"
Error: UPGRADE FAILED: cannot patch "atlantis" with kind StatefulSet: StatefulSet.apps "atlantis" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden
```

We might create a new major release with update steps to fix this. Discussing with the other maintainers. 🙏

_Originally posted by @GMartinez-Sisti in https://github.com/runatlantis/helm-charts/issues/304#issuecomment-2040351415_

**Comment by thomaschaplin** [comment]
I've created a new issue from a comment of an old release as it seems this hasn't yet been documented (or I can't find it, please advise if so).

Would be great to know if this upgrade issue is on the roadmap and when it might be fixed and/or documented how to upgrade without running into the issue mentioned in the original release thread.

**Comment by GMartinez-Sisti** [comment]
Thanks @thomaschaplin! I've been snoozing this issue since I've been on the road lately, but we are still planing to provide an upgrade path, just need to test some options and see which one is the best.

**Comment by thomaschaplin** [comment]
Thanks for the update @GMartinez-Sisti

**Comment by GMartinez-Sisti** [comment]
@thomaschaplin care to take a look at the PR and even test if possible 👼 .

**Comment by thomaschaplin** [comment]
> @thomaschaplin care to take a look at the [PR](https://github.com/runatlantis/helm-charts/pull/381) and even test if possible 👼 .

Thanks @GMartinez-Sisti I'll have a look at this in the morning and get back to you. I'm in the United Kingdom so it's the evening here. I really appreciate the speed of looking at this!

**Comment by thomaschaplin** [comment]
Sorry for the delay, I'll be able to look at this on Tuesday (7th May) @GMartinez-Sisti

**Comment by GMartinez-Sisti** [comment]
> Sorry for the delay, I'll be able to look at this on Tuesday (7th May) @GMartinez-Sisti

Thanks for the feedback! I think we'll merge it before. If required we'll iterate on it.
