### ISSUE TITLE
unable to set enabled params to the helm chart 

### ISSUE THREAD

**Issue by KyriosGN0** [runatlantis/helm-charts#386]
Hi, in my org we set all of our helm chart with enabled params to control deployment in argocd 

how ever in atlantis values schema file there is not enabled param and we can't set additional properties. 

we would like to either have a enabled param or just be able to use additional properties

**Comment by GMartinez-Sisti** [comment]
https://github.com/runatlantis/helm-charts/pull/387#issuecomment-2106269871
