### ISSUE TITLE
Unable to use custom port

### ISSUE THREAD

**Issue by doctahpopp** [runatlantis/helm-charts#420]
You have the ability to set the `targetPort` and `portName` on the service definition, as well as the ability to define `ATLANTIS_PORT` env variable on the `statefulSet` to use a custom port with this workload. 

However, this does not update the port on container spec or the readinessProbes. 

These sections use static blocks 
https://github.com/runatlantis/helm-charts/blob/main/charts/atlantis/templates/statefulset.yaml#L238-L240
https://github.com/runatlantis/helm-charts/blob/main/charts/atlantis/templates/statefulset.yaml#L505-L521

Propose updating the chart to use `service.targetPort` to configure all of the necessary port settings on the chart resources.

Ill cut an MR.

**Comment by doctahpopp** [comment]
@GMartinez-Sisti Have a look at the MR let me know we might be able to get it merged!

**Comment by GMartinez-Sisti** [comment]
Merged on https://github.com/runatlantis/helm-charts/pull/426.
