### ISSUE TITLE
Allow to change 'readOnly' parameter for 'aws-volume' volumeMount

### ISSUE THREAD

**Issue by rkubik-hostersi** [runatlantis/helm-charts#421]
When using Atlantis in AWS EKS, the docker image has to be modified to include `aws-cli`. However, `aws` binary needs write access to the `~/.aws` directory to write some cache files when assuming roles.

Currently, this dir is mounted here: https://github.com/runatlantis/helm-charts/blob/a4ff46cf8deb67cef1f5427300824253a8b340b2/charts/atlantis/templates/statefulset.yaml#L566C1-L566C18 - it would be nice to make a variable out of this.

So far, when trying to call `aws` with assuming roles, I get following error:
```
[Errno 30] Read-only file system: '/home/atlantis/.aws/cli'
```

**Comment by j0can** [comment]
Is this solved, i have the same issue trying to run atlantis on eks resources using a service account:
`[Errno 30] Read-only file system: '/home/atlantis/.aws/cli'`
