### ISSUE TITLE
Upgrade chart to support new version v0.30.0

### ISSUE THREAD

**Issue by seifrajhi** [runatlantis/helm-charts#429]
Hello,

Recently,  the support to OpenTofu was added in the `v0.30.0` version of Atlantis.

It would be great to have the support in the helm chart also.

**Comment by GMartinez-Sisti** [comment]
Hi @seifrajhi, we totally support this!

We have automatic PRs for new atlantis versions, this one is already waiting -> https://github.com/runatlantis/helm-charts/pull/427.

Based on the feature [PR](https://github.com/runatlantis/atlantis/pull/4499) we need to support the new setting in the configs:
> Introduces a --tf-distribution setting that can be set to terraform or opentofu

**Comment by seifrajhi** [comment]
Hello @GMartinez-Sisti I have just created a PR 🤞
