### ISSUE TITLE
Ability to add custom ingress rule for ssl

### ISSUE THREAD

**Issue by vinhlh** [runatlantis/helm-charts#58]
We're using alb controller, and we need to add additional rule for ssl
![image](https://user-images.githubusercontent.com/261283/117784644-59f44d80-b276-11eb-9029-17b26c4d6ac2.png)

**Comment by mcandio** [comment]
I have the same problem, did you manage to solve it?
I'm cloning the repo and customizing the ingress.yaml but it is not what I expect, should be a way to solve this.

**Comment by nitrocode** [comment]
@mcandio @spirosoik @vinhlh 

Don't the current ingress rules allow for overriding the highlighted parameters in the above screenshot?

Please confirm if this is still an issue.

https://github.com/runatlantis/helm-charts/blob/main/charts/atlantis/templates/ingress.yaml

**Comment by nitrocode** [comment]
@mcandio 

The value `ingress.apiVersion` is unset by default

https://github.com/runatlantis/helm-charts/blob/a4e46785625115d3c280fc3337754c0fa5a9f670/charts/atlantis/values.yaml#L213-L214

So `apiVersion` defaults to `extensions/v1beta1` (line 2) but can also be set to a different value depending on the `ingress.apiVersion` (line 4) or the `.Capabilities.APIVersions` (lines 6 and 8).

https://github.com/runatlantis/helm-charts/blob/a4e46785625115d3c280fc3337754c0fa5a9f670/charts/atlantis/templates/ingress.yaml#L1-L9

This is the block that controls whether to use the old `port.number` style or the new `servicePort` style. The latter allows the `use-annotation` value whereas the former does not.

https://github.com/runatlantis/helm-charts/blob/a4e46785625115d3c280fc3337754c0fa5a9f670/charts/atlantis/templates/ingress.yaml#L57-L66

According to this [doc](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/), you should be using `extensions/v1beta1` for your API version so I would explicitly set it in your values and see if it works for you.

```yaml
ingress:
  apiVersion: extensions/v1beta1
```
