### ISSUE TITLE
Add possibility to use init containers in chart

### ISSUE THREAD

**Issue by chinskiy** [runatlantis/helm-charts#6]
Hello!

We are using approach when secrets are mounted to pods via [init containers](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/), but unfortunately, as far as I see this chart does not support this.

Would be happy if this possibility will be added.

If this feature looks good for you - I can provide PR with appropriate changes

**Comment by lkysow** [comment]
A PR sounds good!

**Comment by heruscoder** [comment]
+1 to this.

It will be very useful to install Terragrunt without creating another docker image

**Comment by lkysow** [comment]
Closed by #8.
