### ISSUE TITLE
Create a chart for 0.17

### ISSUE THREAD

**Issue by courteouselk** [runatlantis/helm-charts#60]
Current latest version of this chart refers `0.16.1` while the latest one is `0.17`.  Please create a new helm-chart version for it.

**Comment by billabongrob** [comment]
Submitted a PR a few days back for it.  #56

**Comment by fishpen0** [comment]
This can be closed now?

**Comment by billabongrob** [comment]
> This can be closed now?

I would say so. Branch merged with changes.
