### ISSUE TITLE
How to add config/checksum from values.yaml

### ISSUE THREAD

**Issue by tvarade** [runatlantis/helm-charts#74]
I am using upstream atlantis-helm chart for deploying atlantis on Kubernetes.
Created a configmap in Values.extraManifests
As I do  not  have charts on my local, I can-not add annotation to Statefulset directly.
So when I tried to add this annotation in Values.podTemplate.annotations, I am getting error.

**Annotation**
`
checksum/config: {{ include (print $.Template.BasePath "/aws-configmap.yaml") . | sha256sum }}
`
**Error** 
`
Error: failed to parse values.yaml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{"include (print $.Template.BasePath \\\"/aws-account-configmap.yaml\\\") . | sha256sum":interface {}(nil)}
`

Also if i add this annotation in single quote
`
checksum/config: '{{ include (print $.Template.BasePath "/aws-configmap.yaml") . | sha256sum }}'
`
It will create a deployment but no use as it wont restart pod after any change in configmap.

**Comment by tvarade** [comment]
Any update?

**Comment by kumarsen26** [comment]
Hi,
I may have missed it, but how do we give in values.yaml?

**Comment by AaveshK** [comment]
Have you been able to do that? @kumarsen26
