### ISSUE TITLE
Version 3.14.1 says it's released but it's missing from https://runatlantis.github.io/helm-charts/index.yaml

### ISSUE THREAD

**Issue by andrassy** [runatlantis/helm-charts#89]
This GitHub repo shows 3.14.1 as the latest release (release by the GitHub action) but the latest version in the index at https://runatlantis.github.io/helm-charts/index.yaml is still 3.14.0. 😢

**Comment by lkysow** [comment]
Yeah.. something broke. Can you use 3.14.2 instead.
