### ISSUE TITLE
Ignore ssl verify as an option?

### ISSUE THREAD

**Issue by npsoni88** [runatlantis/helm-charts#93]
I am trying to use the helm chart to deploy atlantis and connect to internal gitlab. I am running into an error where its basically a "x509: signed by unknown authority". I don't find any option to skip sslverify in the helm chart, is it possible?

**Comment by GMartinez-Sisti** [comment]
Looks like this was fixed on https://github.com/runatlantis/helm-charts/pull/163. Can we close this?

**Comment by npsoniembark** [comment]
my apologies for the delay. you are correct, we can close this.
